### DISCUSSION TITLE
DDEV and Xdebug: Debugging and sorting out problems | DDEV

### DISCUSSION THREAD

**Discussion by giscus** [ddev/giscus-comments#10] [ddev.com comments]
# DDEV and Xdebug: Debugging and sorting out problems | DDEV

How Xdebug works with DDEV, and how to debug problems

https://ddev.com/blog/xdebug-debugging/

**Comment by kickblast** [comment]
Adding this hook in `config.yaml` make it work back!

```yaml
hooks:
  post-start:
    # resolve a xdebug conflict with phpstorm and windows 11 + WSL
    - exec: IP=$(ip -4 route show default | awk '{print $3}') && ddev config global --xdebug-ide-location=$IP`
```
